name: VectorDB Sync

on:
  # Run when a PR is merged into main
  pull_request:
    types: [closed]

  # Run on direct pushes to main branch
  push:
    branches:
      - main

jobs:
  sync:
    # For PR: only if merged into main
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Detect changed files (root + submodules)
        run: |
          echo "🔎 Detecting changes..."
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Push to main branch detected"
            git diff --name-status HEAD^ HEAD > changed_files.txt || true
          else
            echo "Pull request merged into main detected"
            git diff --name-status origin/main HEAD > changed_files.txt || true
          fi

          cat changed_files.txt

          echo "🔎 Detecting submodule pointer changes..."
          git diff --submodule > submodule_changes.txt || true
          cat submodule_changes.txt

          echo "🔎 Expanding submodule changes into file-level diffs..."
          while read -r line; do
            submodule=$(echo "$line" | awk '{print $1}')
            oldsha=$(echo "$line" | awk '{print $2}')
            newsha=$(echo "$line" | awk '{print $3}')
            if [ -n "$submodule" ] && [ -n "$oldsha" ] && [ -n "$newsha" ]; then
              echo "📂 Submodule: $submodule ($oldsha → $newsha)"
              pushd $submodule > /dev/null
              git fetch origin $oldsha $newsha || true
              git diff --name-status $oldsha $newsha | sed "s|^|$submodule/|" >> ../changed_files.txt
              popd > /dev/null
            fi
          done < <(git diff --submodule | grep Submodule)

          echo "✅ Final changed files list:"
          cat changed_files.txt

#      - name: Run VectorDB Sync
#        env:
#          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#        run: |
#          python scripts/sync_pinecone.py changed_files.txt
